### ISSUE TITLE
Delete crate on crates.io

### ISSUE THREAD

**Issue by kvsari** [kvsari/shed#1]
@carols10cents Is it possible to delete the crate for this project on crates.io? This project isn't going anywhere and I don't want to squat on the name.

**Comment by carols10cents** [comment]
Hi, it's not possible to delete crates. What I would recommend is that you publish a new version with the following:

- A description that says you're willing to give up the name and a way someone should contact you if they want the name
- A maintenance status of "looking-for-maintainer" (explanation from docs https://doc.rust-lang.org/cargo/reference/manifest.html#package-metadata):

    > # Maintenance: `status` is required Available options are `actively-developed`,
    > # `passively-maintained`, `as-is`, `none`, `experimental`, `looking-for-maintainer`
    > # and `deprecated`.
    > maintenance = { status = "..." }

If you don't want to do this and just want to be rid of this crate, please add me as an owner and I will be happy to take these steps for you and manage transferring the crate to someone else in the future.

We do have a github organization for abandoned projects: https://github.com/rust-unofficial but that's mostly for abandoned *code* that someone might want to pick up, but there's not really a great way to just give this org the *crate name*, because [team owners are only allowed to publish/yank, not add/remove owners](https://doc.rust-lang.org/cargo/reference/publishing.html#cargo-owner), so the crate needs a username owner on crates.io to allow transfers in the future. I am offering to be that username if that's what you'd like.

**Comment by kvsari** [comment]
@carols10cents Hi, thank you for your kind offer to take ownership of the crate. In the future I'll publish a crate when I have a bare minimum of working code ready and not before. If someone has already taken the name in the meantime, tough.

Once you have taken ownership and removed me I'll delete this repo.

**Comment by carols10cents** [comment]
Done!

**Comment by kvsari** [comment]
@carols10cents Thank you very much. I greatly appreciate you taking this off my hands.
